version: '3.9'
services:
  rom-test-3-6:
    build:
      context: .
      dockerfile: Dockerfile.3.6
    environment:
      REDIS_HOST: redis-data-storage
      REDIS_PORT: 6379
      REDIS_DB: 15
      PYTHONPATH: /app
    links:
      - redis-data-storage
  redis-data-storage:
    image: redis:7-bullseye
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save ""
