ARG PYTHON_VERSION="3.11"

FROM python:${PYTHON_VERSION}-bullseye
ARG PYTHON_VERSION
ARG PY="python${PYTHON_VERSION}"

ENV PYTHON_VERSION=$PYTHON_VERSION

WORKDIR /app

RUN ${PY} -m pip install --upgrade pip
COPY requirements.txt .
RUN ${PY} -m pip install -r requirements.txt

# need rom
COPY rom/*.py rom/
# and need the tests too
COPY test/* rom_tests/

CMD ${PY} rom_tests/test_rom.py
