FROM python:3.5

WORKDIR /app

COPY requirements.txt .

RUN python3.5 -m pip install -r requirements.txt

# need rom
COPY rom/*.py rom/
# and need the tests too
COPY test/* rom_tests/

# Note: needs access to Redis; assumes localhost:6879
CMD ["python3.5", "-m", "rom_tests.test_rom"]